local RECEIVED_INITIAL_TEXT = 'received initial text'
local SENT_PHONE_CONFIRMATION_REQUEST = 'sent phone confirmation text'
local RECEIVED_CONFIRMED_PHONE_NUMBER = 'received phone number'
local SENT_PIN_REQUEST = 'sent pin request'
local RECEIVED_PIN = 'received pin'
local SENT_CAR_OPTIONS = 'sent car options'